version: '3.7'
services:
  db:
    container_name: db_application
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
      # Uncomment if you want to load schema before migrations or any declarations
      # - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    tty: true
    ports:
      - '54001:5432'
  web:
    container_name: web_application
    build:
      context: .
    env_file: ./.env
    depends_on:
      - db
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - '5000:5000'
      - 127.0.0.1:9223:9223
    environment:
      - DB_HOST=db_application
    command: npm start
  migration:
    build:
      context: .
    command:
      ['./wait-for-it/wait-for-it.sh', 'db:5432', '--', 'npm', 'run', 'migrate']
    links:
      - db
    depends_on:
      - db
    env_file: ./.env
    environment:
      - DB_HOST=db_application
volumes:
  pg_data: null
